spring:
  application:
    name: docker-service

# PostgreSQL Database Connection Settings (Placeholder to resolve for Docker host and fallback for local machine)
  datasource:
    url: jdbc:postgresql://${DB_HOST_URL:localhost}:5432/${DB_NAME:studentDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true